spring.application.name=my-pocket-book-api
spring.datasource.url=jdbc:mysql://localhost:3306/mypocket?useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

springdoc.swagger-ui.path=/swagger-ui.html

kakao.api.baseurl=https://dapi.kakao.com
kakao.api.path.book=/v3/search/book
kakao.restapi.key=KakaoAK ${KAKAO_API_KEY}

jwt.secret.key=${SECRET_KEY}

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache
spring.cache.type=redis

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
