
host = http://localhost:8080
headless = false
users = 100
spawn-rate = 10
run-time = 300s


loglevel = INFO
logfile = locust.log


html = reports/report.html
csv = reports/results


web-host = 0.0.0.0
web-port = 8089

